---
name: Lint Project
"on": # quoted to avoid YAML lint 'truthy' warning
  push:
    branches:
      - "**" # All branches
      - "!gh-pages" # Except gh-pages
      - '!develop' # Except develop
      - '!main' # Except main
      - "!master" # Except master
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

permissions: { }

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: develop
          VALIDATE_BASH_EXEC: false
          VALIDATE_SHELL_SHFMT: false
          GITHUB_TOKEN: ${{ github.token }}
          VALIDATE_CHECKOV: false
          # REENABLE 
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_STANDARD: false

          VALIDATE_JSON_PRETTIER: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
